### ISSUE TITLE
1.9.0 release not working for python 2.7

### ISSUE THREAD

**Issue by spartacus06** [LudovicRousseau/pyscard#12]
```
$ python
Python 2.7.10 (default, Jul  5 2015, 14:15:43) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import smartcard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/smartcard/__init__.py", line 32, in <module>
    from smartcard.System import listReaders
  File "/usr/lib64/python2.7/site-packages/smartcard/System.py", line 28, in <module>
    import smartcard.reader.ReaderFactory
  File "/usr/lib64/python2.7/site-packages/smartcard/reader/ReaderFactory.py", line 34, in <module>
    from smartcard.pcsc.PCSCReader import PCSCReader
  File "/usr/lib64/python2.7/site-packages/smartcard/pcsc/PCSCReader.py", line 28, in <module>
    from smartcard.pcsc.PCSCContext import PCSCContext
  File "/usr/lib64/python2.7/site-packages/smartcard/pcsc/PCSCContext.py", line 27, in <module>
    from smartcard.scard import *
  File "/usr/lib64/python2.7/site-packages/smartcard/scard/__init__.py", line 1, in <module>
    from smartcard.scard.scard import *
  File "/usr/lib64/python2.7/site-packages/smartcard/scard/scard.py", line 830, in <module>
    SCARD_SCOPE_USER = _scard.SCARD_SCOPE_USER
AttributeError: 'module' object has no attribute 'SCARD_SCOPE_USER'
```

Seems like something up with swig, but I'm not a python guy.  Any help appreciated!

**Comment by LudovicRousseau** [comment]
How did you install pyscard? from source code?
What version of pyscard do you use?

**Comment by spartacus06** [comment]
Gah.  I was building from source (rpmbuild), but some compiler flags in the build env were messing it up.   Nevermind!

**Comment by cluck** [comment]
I just bumped into this error on OSX 10.10 using `pip install --user pyscard`.

This is related to swig/swig#250. In other words, for newer versions of Swig the generated `smartcard/scard/scard,py` is different and not backward compatible to files generated by previous versions of Swig. Thus, `smartcard/scard/scard,py` should be re-generated too before swig is invoked during installation.

Or at least, the following patch could be applied to support newer versions of Swig, but I think this is not the right way to go:

```
--- ./smartcard/scard/scard.py.orig	2015-09-05 17:23:55.000000000 +0200
+++ ./smartcard/scard/scard.py	2015-09-05 17:24:00.000000000 +0200
@@ -827,6 +827,158 @@
   return _scard.SCardGetErrorMessage(*args)
 error = _scard.error
 
+try:
+    _scard.SCARD_SCOPE_USER_swigconstant
+except AttributeError:
+    pass
+else:
+    _scard.SCARD_SCOPE_USER_swigconstant(_scard)
+    _scard.SCARD_SCOPE_TERMINAL_swigconstant(_scard)
+    _scard.SCARD_SCOPE_SYSTEM_swigconstant(_scard)
+    _scard.SCARD_SHARE_SHARED_swigconstant(_scard)
+    _scard.SCARD_SHARE_EXCLUSIVE_swigconstant(_scard)
+    _scard.SCARD_SHARE_DIRECT_swigconstant(_scard)
+    _scard.SCARD_LEAVE_CARD_swigconstant(_scard)
+    _scard.SCARD_RESET_CARD_swigconstant(_scard)
+    _scard.SCARD_UNPOWER_CARD_swigconstant(_scard)
+    _scard.SCARD_EJECT_CARD_swigconstant(_scard)
+    _scard.SCARD_STATE_UNAWARE_swigconstant(_scard)
+    _scard.SCARD_STATE_IGNORE_swigconstant(_scard)
+    _scard.SCARD_STATE_CHANGED_swigconstant(_scard)
+    _scard.SCARD_STATE_UNKNOWN_swigconstant(_scard)
+    _scard.SCARD_STATE_UNAVAILABLE_swigconstant(_scard)
+    _scard.SCARD_STATE_EMPTY_swigconstant(_scard)
+    _scard.SCARD_STATE_PRESENT_swigconstant(_scard)
+    _scard.SCARD_STATE_ATRMATCH_swigconstant(_scard)
+    _scard.SCARD_STATE_EXCLUSIVE_swigconstant(_scard)
+    _scard.SCARD_STATE_INUSE_swigconstant(_scard)
+    _scard.SCARD_STATE_MUTE_swigconstant(_scard)
+    _scard.SCARD_STATE_UNPOWERED_swigconstant(_scard)
+    _scard.SCARD_PROTOCOL_UNSET_swigconstant(_scard)
+    _scard.SCARD_PROTOCOL_T0_swigconstant(_scard)
+    _scard.SCARD_PROTOCOL_T1_swigconstant(_scard)
+    _scard.SCARD_PROTOCOL_RAW_swigconstant(_scard)
+    _scard.SCARD_PROTOCOL_T15_swigconstant(_scard)
+    _scard.SCARD_PROTOCOL_ANY_swigconstant(_scard)
+    _scard.SCARD_PROTOCOL_UNDEFINED_swigconstant(_scard)
+    _scard.SCARD_PROTOCOL_OPTIMAL_swigconstant(_scard)
+    _scard.SCARD_PROTOCOL_Tx_swigconstant(_scard)
+    _scard.SCARD_PROTOCOL_DEFAULT_swigconstant(_scard)
+    _scard.SCARD_PCI_T0_swigconstant(_scard)
+    _scard.SCARD_PCI_T1_swigconstant(_scard)
+    _scard.SCARD_PCI_RAW_swigconstant(_scard)
+    _scard.SCARD_ATTR_VENDOR_NAME_swigconstant(_scard)
+    _scard.SCARD_ATTR_VENDOR_IFD_TYPE_swigconstant(_scard)
+    _scard.SCARD_ATTR_VENDOR_IFD_VERSION_swigconstant(_scard)
+    _scard.SCARD_ATTR_VENDOR_IFD_SERIAL_NO_swigconstant(_scard)
+    _scard.SCARD_ATTR_CHANNEL_ID_swigconstant(_scard)
+    _scard.SCARD_ATTR_ASYNC_PROTOCOL_TYPES_swigconstant(_scard)
+    _scard.SCARD_ATTR_DEFAULT_CLK_swigconstant(_scard)
+    _scard.SCARD_ATTR_MAX_CLK_swigconstant(_scard)
+    _scard.SCARD_ATTR_DEFAULT_DATA_RATE_swigconstant(_scard)
+    _scard.SCARD_ATTR_MAX_DATA_RATE_swigconstant(_scard)
+    _scard.SCARD_ATTR_MAX_IFSD_swigconstant(_scard)
+    _scard.SCARD_ATTR_SYNC_PROTOCOL_TYPES_swigconstant(_scard)
+    _scard.SCARD_ATTR_POWER_MGMT_SUPPORT_swigconstant(_scard)
+    _scard.SCARD_ATTR_USER_TO_CARD_AUTH_DEVICE_swigconstant(_scard)
+    _scard.SCARD_ATTR_USER_AUTH_INPUT_DEVICE_swigconstant(_scard)
+    _scard.SCARD_ATTR_CHARACTERISTICS_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_PROTOCOL_TYPE_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_CLK_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_F_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_D_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_N_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_W_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_IFSC_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_IFSD_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_BWT_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_CWT_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_EBC_ENCODING_swigconstant(_scard)
+    _scard.SCARD_ATTR_EXTENDED_BWT_swigconstant(_scard)
+    _scard.SCARD_ATTR_ICC_PRESENCE_swigconstant(_scard)
+    _scard.SCARD_ATTR_ICC_INTERFACE_STATUS_swigconstant(_scard)
+    _scard.SCARD_ATTR_CURRENT_IO_STATE_swigconstant(_scard)
+    _scard.SCARD_ATTR_ATR_STRING_swigconstant(_scard)
+    _scard.SCARD_ATTR_ICC_TYPE_PER_ATR_swigconstant(_scard)
+    _scard.SCARD_ATTR_ESC_RESET_swigconstant(_scard)
+    _scard.SCARD_ATTR_ESC_CANCEL_swigconstant(_scard)
+    _scard.SCARD_ATTR_ESC_AUTHREQUEST_swigconstant(_scard)
+    _scard.SCARD_ATTR_MAXINPUT_swigconstant(_scard)
+    _scard.SCARD_ATTR_DEVICE_UNIT_swigconstant(_scard)
+    _scard.SCARD_ATTR_DEVICE_IN_USE_swigconstant(_scard)
+    _scard.SCARD_ATTR_DEVICE_FRIENDLY_NAME_A_swigconstant(_scard)
+    _scard.SCARD_ATTR_DEVICE_SYSTEM_NAME_A_swigconstant(_scard)
+    _scard.SCARD_ATTR_DEVICE_FRIENDLY_NAME_W_swigconstant(_scard)
+    _scard.SCARD_ATTR_DEVICE_SYSTEM_NAME_W_swigconstant(_scard)
+    _scard.SCARD_ATTR_SUPRESS_T1_IFS_REQUEST_swigconstant(_scard)
+    _scard.SCARD_ATTR_DEVICE_FRIENDLY_NAME_swigconstant(_scard)
+    _scard.SCARD_ATTR_DEVICE_SYSTEM_NAME_swigconstant(_scard)
+    _scard.SCARD_S_SUCCESS_swigconstant(_scard)
+    _scard.SCARD_F_INTERNAL_ERROR_swigconstant(_scard)
+    _scard.SCARD_E_CANCELLED_swigconstant(_scard)
+    _scard.SCARD_E_INVALID_HANDLE_swigconstant(_scard)
+    _scard.SCARD_E_INVALID_PARAMETER_swigconstant(_scard)
+    _scard.SCARD_E_INVALID_TARGET_swigconstant(_scard)
+    _scard.SCARD_E_NO_MEMORY_swigconstant(_scard)
+    _scard.SCARD_F_WAITED_TOO_LONG_swigconstant(_scard)
+    _scard.SCARD_E_INSUFFICIENT_BUFFER_swigconstant(_scard)
+    _scard.SCARD_E_UNKNOWN_READER_swigconstant(_scard)
+    _scard.SCARD_E_TIMEOUT_swigconstant(_scard)
+    _scard.SCARD_E_SHARING_VIOLATION_swigconstant(_scard)
+    _scard.SCARD_E_NO_SMARTCARD_swigconstant(_scard)
+    _scard.SCARD_E_UNKNOWN_CARD_swigconstant(_scard)
+    _scard.SCARD_E_CANT_DISPOSE_swigconstant(_scard)
+    _scard.SCARD_E_PROTO_MISMATCH_swigconstant(_scard)
+    _scard.SCARD_E_NOT_READY_swigconstant(_scard)
+    _scard.SCARD_E_INVALID_VALUE_swigconstant(_scard)
+    _scard.SCARD_E_SYSTEM_CANCELLED_swigconstant(_scard)
+    _scard.SCARD_F_COMM_ERROR_swigconstant(_scard)
+    _scard.SCARD_F_UNKNOWN_ERROR_swigconstant(_scard)
+    _scard.SCARD_E_INVALID_ATR_swigconstant(_scard)
+    _scard.SCARD_E_NOT_TRANSACTED_swigconstant(_scard)
+    _scard.SCARD_E_READER_UNAVAILABLE_swigconstant(_scard)
+    _scard.SCARD_E_PCI_TOO_SMALL_swigconstant(_scard)
+    _scard.SCARD_E_READER_UNSUPPORTED_swigconstant(_scard)
+    _scard.SCARD_E_DUPLICATE_READER_swigconstant(_scard)
+    _scard.SCARD_E_CARD_UNSUPPORTED_swigconstant(_scard)
+    _scard.SCARD_E_NO_SERVICE_swigconstant(_scard)
+    _scard.SCARD_E_SERVICE_STOPPED_swigconstant(_scard)
+    _scard.SCARD_E_NO_READERS_AVAILABLE_swigconstant(_scard)
+    _scard.SCARD_E_UNSUPPORTED_FEATURE_swigconstant(_scard)
+    _scard.SCARD_W_UNSUPPORTED_CARD_swigconstant(_scard)
+    _scard.SCARD_W_UNRESPONSIVE_CARD_swigconstant(_scard)
+    _scard.SCARD_W_UNPOWERED_CARD_swigconstant(_scard)
+    _scard.SCARD_W_RESET_CARD_swigconstant(_scard)
+    _scard.SCARD_W_REMOVED_CARD_swigconstant(_scard)
+    _scard.SCARD_W_SECURITY_VIOLATION_swigconstant(_scard)
+    _scard.SCARD_W_WRONG_CHV_swigconstant(_scard)
+    _scard.SCARD_W_CHV_BLOCKED_swigconstant(_scard)
+    _scard.SCARD_W_EOF_swigconstant(_scard)
+    _scard.SCARD_W_CANCELLED_BY_USER_swigconstant(_scard)
+    _scard.SCARD_W_CARD_NOT_AUTHENTICATED_swigconstant(_scard)
+    _scard.SCARD_E_UNEXPECTED_swigconstant(_scard)
+    _scard.SCARD_E_ICC_INSTALLATION_swigconstant(_scard)
+    _scard.SCARD_E_ICC_CREATEORDER_swigconstant(_scard)
+    _scard.SCARD_E_DIR_NOT_FOUND_swigconstant(_scard)
+    _scard.SCARD_E_FILE_NOT_FOUND_swigconstant(_scard)
+    _scard.SCARD_E_NO_DIR_swigconstant(_scard)
+    _scard.SCARD_E_NO_FILE_swigconstant(_scard)
+    _scard.SCARD_E_NO_ACCESS_swigconstant(_scard)
+    _scard.SCARD_E_WRITE_TOO_MANY_swigconstant(_scard)
+    _scard.SCARD_E_BAD_SEEK_swigconstant(_scard)
+    _scard.SCARD_E_INVALID_CHV_swigconstant(_scard)
+    _scard.SCARD_E_UNKNOWN_RES_MNG_swigconstant(_scard)
+    _scard.SCARD_E_NO_SUCH_CERTIFICATE_swigconstant(_scard)
+    _scard.SCARD_E_CERTIFICATE_UNAVAILABLE_swigconstant(_scard)
+    _scard.SCARD_E_COMM_DATA_LOST_swigconstant(_scard)
+    _scard.SCARD_E_NO_KEY_CONTAINER_swigconstant(_scard)
+    _scard.SCARD_E_SERVER_TOO_BUSY_swigconstant(_scard)
+    _scard.INVALID_HANDLE_swigconstant(_scard)
+    _scard.SCARD_P_SHUTDOWN_swigconstant(_scard)
+    _scard.INFINITE_swigconstant(_scard)
+    _scard.resourceManager_swigconstant(_scard)
+    _scard.resourceManagerSubType_swigconstant(_scard)
+    
 SCARD_SCOPE_USER = _scard.SCARD_SCOPE_USER
 SCARD_SCOPE_TERMINAL = _scard.SCARD_SCOPE_TERMINAL
 SCARD_SCOPE_SYSTEM = _scard.SCARD_SCOPE_SYSTEM
```

**Comment by LudovicRousseau** [comment]
@cluck do you have a patch to propose? I am not a setuptools expert.

**Comment by 0xABD** [comment]
The same behavior can be seen on Windows with Python 2.7.10. I tried to manually run latest swig and regenerate the files as suggested with no result.

**Comment by kaminoo** [comment]
+1 for me
Working on OSX 10.10.5 and python 2.7.10
Doing `pip install pyscard` will install 1.9.0 and can't run not even the examples with error `AttributeError: 'module' object has no attribute 'SCARD_SCOPE_USER'`
Installing using `pip install <url to master.zip>` makes a different error saying `scard module does not exist`

Any help? Does python 3 fix this issue?
Any workarounds?
I couldn't understand what other user this as workaround with swig and such.

Anything I can help, let me know.

**Comment by cluck** [comment]
I think the problem happens in the process of creating the source archives that are uploaded to sourceforce and pypi: they differ from the output of `python setup.py sdist` on a clean checkout and in particular they contain the file `smartcard/scard/scard.py`.

If this file wasn't present in the source, it would be created in the `build_ext` step, in a format that is suitable to the generated wrapper.

**Comment by LudovicRousseau** [comment]
@cluck I think you are right.
Can someone propose a patch so that ``python setup.py sdist`` does the correct thing?

**Comment by cluck** [comment]
I think that starting with a clean checkout and running `python setup.py sdist` as the sole command is the only option for now.

I suspect it to be a bug in the realm of Distutils/Setuptools that `python setup.py sdist` picks up files excluded in in the `MANIFEST.in` and not being idempotent before/after running `python setup.py build` or other commands.
